typography_spectrum: 0.38921159505844116
color:
  brandStrength: 0.4746310885529965
  lightness: 0.5892305583693087
  saturation: 0.7336322069168091
  rhythmicContrast: 0.46266314573585987
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
layout_spectrum: 0.3331880527548492
author:
  name: fawn pierre
  email: fawn@smartypup.com
  url: smartypup.com
logo: null
name: smartypup
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3469044-cdea-4f8c-8162-a679f39a7fa4.png
title: SmartyPup!
description: for dogs. for people
